#!/bin/sh
# Trunk post_build hook (see app/Trunk.toml): writes sw.js into the staging
# directory Trunk is about to publish as dist.
#
# Trunk v0.21.14 facts this relies on:
#   - post_build runs AFTER index.html is written to $TRUNK_STAGING_DIR
#     (= <dist>/.stage) and BEFORE staging replaces dist — so the right
#     place to write is $TRUNK_STAGING_DIR, never $TRUNK_DIST_DIR.
#   - The hook's cwd is the directory holding Trunk.toml (app/), not dist.
#   - TRUNK_PROFILE is "debug" or "release".
set -eu

STAGE="${TRUNK_STAGING_DIR:?gen-sw.sh must run as a Trunk post_build hook}"
HOOKS="$(cd "$(dirname "$0")" && pwd)"

# Debug builds (`trunk serve`) get a stub that caches nothing and cleans up
# after any release worker previously seen on this origin — a dev loop must
# never be served yesterday's wasm from a cache.
if [ "${TRUNK_PROFILE:-debug}" != "release" ]; then
    cp "$HOOKS/sw-debug.js" "$STAGE/sw.js"
    echo "gen-sw.sh: debug build — wrote the no-cache stub sw.js"
    exit 0
fi

# Every staged file, one per line, stable order. Trunk emits flat hashed
# names (no spaces or quotes); fail the build loudly if that ever changes
# rather than emit a corrupt manifest.
FILES=$(cd "$STAGE" && find . -type f ! -name sw.js | sed 's|^\./||' | LC_ALL=C sort)
case "$FILES" in
    *" "*|*"'"*|*'"'*) echo "gen-sw.sh: a dist filename needs quoting:" >&2
                       printf '%s\n' "$FILES" >&2; exit 1 ;;
esac

# Cache name: a hash over every file's NAME and BYTES, so any change — even
# a rebuilt index.html whose asset names stayed the same — yields a new
# cache, and activate drops the old one. sha256sum on Linux (Docker rust:1
# has coreutils), shasum on macOS.
if command -v sha256sum >/dev/null 2>&1; then SHA=sha256sum; else SHA="shasum -a 256"; fi
HASH=$(
    cd "$STAGE"
    {
        printf '%s\n' "$FILES"
        printf '%s\n' "$FILES" | while IFS= read -r f; do cat "./$f"; done
    } | $SHA | cut -c1-16
)

{
    printf '// Generated by app/hooks/gen-sw.sh at build time. Do not edit this copy.\n'
    printf "const CACHE = 'cmitt-sw-%s';\n" "$HASH"
    printf 'const MANIFEST = [\n'
    # Exactly the staged files, nothing added. './index.html' is already in
    # FILES and IS the shell. Do NOT reinstate a separate './' entry: it
    # precaches the same document a second time — a second full fetch of
    # index.html on every install — and it buys nothing, because
    # sw-body.js's navigate() already falls back to the cached
    # './index.html' whenever the exact request URL misses, which is
    # precisely what a bare directory URL ('/' or '/cmi-timetable/') is.
    # That fallback is what makes offline deep links and share URLs work
    # (t74), so it is './index.html' that must survive, not './'.
    printf '%s\n' "$FILES" | sed "s|.*|  './&',|"
    printf '];\n'
    cat "$HOOKS/sw-body.js"
} > "$STAGE/sw.js"

echo "gen-sw.sh: sw.js precaches $(printf '%s\n' "$FILES" | wc -l) files as cmitt-sw-$HASH"
