//! Application state: one `App` handle of copyable signals provided through
//! context, plus every user action (all undoable ones go through `act`).

use crate::{domx, storage};
use leptos::prelude::*;
use serde::{Deserialize, Serialize};
use ttcore::diff::SnapshotDiff;
use ttcore::merge::Conflict;
use ttcore::model::{
    Course, Day, Meeting, OverridesStore, ParseReport, ScheduleStatus, Slot, Snapshot,
    SourceTier,
};

pub const APP_VERSION: &str = env!("CARGO_PKG_VERSION");
pub const GIT_COMMIT: &str = env!("APP_GIT_COMMIT");
pub const BUILD_TIME: &str = env!("APP_BUILD_TIME");

pub fn bundled_snapshot() -> Snapshot {
    serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/bundled_snapshot.json")))
        .expect("bundled snapshot is valid (generated by build.rs)")
}

pub fn bundled_report() -> ParseReport {
    serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/bundled_report.json")))
        .expect("bundled report is valid")
}

// ---------------------------------------------------------------------------
// Preferences & filters (persisted)
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum ThemePref {
    #[default]
    Auto,
    Light,
    Dark,
}

#[derive(Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum Density {
    #[default]
    Comfortable,
    Compact,
}

#[derive(Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum Tab {
    #[default]
    MyTimetable,
    MyCourses,
    MasterGrid,
    Catalog,
    Halls,
}

impl Tab {
    pub const ALL: [Tab; 5] = [
        Tab::MyTimetable,
        Tab::MyCourses,
        Tab::MasterGrid,
        Tab::Catalog,
        Tab::Halls,
    ];

    pub fn label(&self) -> &'static str {
        match self {
            Tab::MyTimetable => "My timetable",
            Tab::MyCourses => "My courses",
            Tab::MasterGrid => "Master grid",
            Tab::Catalog => "Catalog",
            Tab::Halls => "Halls",
        }
    }
}

/// Facets are multi-select: OR within a facet, AND across facets.
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Filters {
    pub branches: Vec<String>,
    pub instructors: Vec<String>,
    pub days: Vec<Day>,
    pub slot_starts: Vec<u16>,
    pub halls: Vec<String>,
    /// "2", "4", … or "?" for unknown.
    pub credits: Vec<String>,
    /// "optional", "unscheduled", "custom".
    pub flags: Vec<String>,
    pub text: String,
    /// "Fits my schedule": hide anything overlapping the current selection.
    pub fits: bool,
}

impl Filters {
    pub fn active_count(&self) -> usize {
        self.branches.len()
            + self.instructors.len()
            + self.days.len()
            + self.slot_starts.len()
            + self.halls.len()
            + self.credits.len()
            + self.flags.len()
            + usize::from(!self.text.trim().is_empty())
            + usize::from(self.fits)
    }

    pub fn is_empty(&self) -> bool {
        self.active_count() == 0
    }
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Prefs {
    pub theme: ThemePref,
    pub density: Density,
    pub filters: Filters,
    /// ms since epoch of the last automatic update attempt (12 h throttle).
    pub last_update_attempt: f64,
    pub tab: Tab,
    pub halls_day: Day,
}

impl Default for Prefs {
    fn default() -> Self {
        Prefs {
            theme: ThemePref::default(),
            density: Density::default(),
            filters: Filters::default(),
            last_update_attempt: 0.0,
            tab: Tab::default(),
            halls_day: Day::Mon,
        }
    }
}

// ---------------------------------------------------------------------------
// Transient state
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Route {
    Planner,
    Developer,
}

#[derive(Clone, PartialEq)]
pub struct SyncMeta {
    pub fetched_at: f64,
    pub source: SourceTier,
    pub updating: bool,
    /// Live per-tier progress line while updating ("trying proxy 1 of 2…").
    pub progress: String,
}

#[derive(Clone, PartialEq)]
pub struct Toast {
    pub id: u64,
    pub text: String,
    pub undo: bool,
}

thread_local! {
    /// Toasts currently under the pointer or holding keyboard focus —
    /// auto-dismiss pauses for them so the reader sets the pace, not the
    /// timer. Deliberately NOT a signal: hover must not re-render toasts.
    static HOVERED_TOASTS: std::cell::RefCell<std::collections::HashSet<u64>> =
        std::cell::RefCell::new(std::collections::HashSet::new());
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum BannerKind {
    Info,
    Warn,
}

#[derive(Clone, PartialEq)]
pub struct Banner {
    pub kind: BannerKind,
    pub text: String,
    /// Sticky banners (e.g. the corrupt-data notice) survive the start of
    /// the next update attempt; ordinary failure banners are cleared there.
    pub sticky: bool,
}

#[derive(Clone, PartialEq)]
pub enum Dialog {
    /// Course details popover (any compact rendering opens this).
    Details(String),
    /// "My data": everything saved in the browser, with removal options.
    MyData,
    /// Create/edit a meeting override. `create` = "Give it a time".
    EditMeeting {
        course: String,
        ov_id: Option<u64>,
        base: Option<Meeting>,
        init: Meeting,
        create: bool,
    },
    Conflicts,
    Export { scope: Option<String> },
    Share,
    WhatChanged,
}

/// An in-flight pointer drag.
#[derive(Clone, PartialEq)]
pub struct DragState {
    pub spec: DragSpec,
    pub pointer_id: i32,
    /// Threshold/long-press passed; ghost is showing.
    pub started: bool,
    pub start_x: f64,
    pub start_y: f64,
    pub x: f64,
    pub y: f64,
    pub over: Option<(Day, u16)>,
    /// Set when hovering a Halls-view cell: dropping there also moves the
    /// meeting into that row's hall.
    pub over_hall: Option<String>,
    /// Touch drags lift only after a 350 ms long-press.
    pub awaiting_longpress: bool,
}

#[derive(Clone, PartialEq)]
pub struct DragSpec {
    pub code: String,
    /// Existing override being moved (its id), if any.
    pub ov_id: Option<u64>,
    /// The official meeting being moved (None ⇒ unscheduled tray / created).
    pub base: Option<Meeting>,
    /// Hall carried over into the drop (editable afterwards).
    pub hall: Option<String>,
    pub from_master: bool,
    pub label: String,
}

/// Keyboard move mode: focus a chip → M → arrows → Enter.
#[derive(Clone, PartialEq)]
pub struct MoveMode {
    pub spec: DragSpec,
    pub cursor: (Day, u16),
}

#[derive(Clone)]
pub struct UndoEntry {
    pub label: String,
    pub selection: Vec<String>,
    pub overrides: OverridesStore,
}

#[derive(Clone, Default)]
pub struct UndoStack {
    pub undo: Vec<UndoEntry>,
    pub redo: Vec<UndoEntry>,
}

const UNDO_MAX: usize = 100;

#[derive(Clone, PartialEq)]
pub struct FetchLogEntry {
    pub at: f64,
    pub tier: String,
    pub url: String,
    pub status: Option<u16>,
    pub duration_ms: f64,
    pub bytes: usize,
    pub error: Option<String>,
}

#[derive(Clone, PartialEq)]
pub struct StoredReport {
    pub at: f64,
    pub source: String,
    pub report: ParseReport,
}

/// One effective (post-override) meeting of a course.
#[derive(Clone, PartialEq)]
pub struct EffMeeting {
    pub meeting: Meeting,
    pub overridden: bool,
    pub ov_id: Option<u64>,
    pub base: Option<Meeting>,
    pub user_created: bool,
}

#[derive(Clone, PartialEq)]
pub struct ClashPair {
    pub a: String,
    pub b: String,
    pub day: Day,
    pub a_slot: Slot,
    pub b_slot: Slot,
}

// ---------------------------------------------------------------------------
// The App handle
// ---------------------------------------------------------------------------

#[derive(Clone, Copy)]
pub struct App {
    pub snapshot: RwSignal<Snapshot>,
    pub sync: RwSignal<SyncMeta>,
    pub selection: RwSignal<Vec<String>>,
    pub overrides: RwSignal<OverridesStore>,
    pub prefs: RwSignal<Prefs>,
    pub undo_stack: RwSignal<UndoStack>,
    pub toasts: RwSignal<Vec<Toast>>,
    pub toast_seq: RwSignal<u64>,
    pub banner: RwSignal<Option<Banner>>,
    pub conflicts: RwSignal<Vec<Conflict>>,
    pub what_changed: RwSignal<Option<SnapshotDiff>>,
    /// Selected codes that vanished upstream ("No longer on CMI's timetable").
    pub removed_upstream: RwSignal<Vec<String>>,
    /// Unknown codes from a shared URL (dismissible warning chips).
    pub unknown_codes: RwSignal<Vec<String>>,
    pub fetch_log: RwSignal<Vec<FetchLogEntry>>,
    pub reports: RwSignal<Vec<StoredReport>>,
    pub route: RwSignal<Route>,
    pub dialog: RwSignal<Option<Dialog>>,
    pub drag: RwSignal<Option<DragState>>,
    pub move_mode: RwSignal<Option<MoveMode>>,
    /// Developer-mode simulator: force a specific tier on the next update.
    pub force_tier: RwSignal<Option<String>>,
    /// aria-live announcements (keyboard move mode, etc.).
    pub announce: RwSignal<String>,
    /// Drag & drop (pointer and keyboard move mode) only works while edit
    /// mode is on — toggled per session from the grid toolbars.
    pub edit_mode: RwSignal<bool>,
}

impl App {
    pub fn use_ctx() -> App {
        expect_context::<App>()
    }

    // -- feedback ----------------------------------------------------------

    pub fn toast(&self, text: impl Into<String>) {
        self.push_toast(text.into(), false);
    }

    pub fn toast_undo(&self, text: impl Into<String>) {
        self.push_toast(text.into(), true);
    }

    fn push_toast(&self, text: String, undo: bool) {
        let id = self.toast_seq.get_untracked() + 1;
        self.toast_seq.set(id);
        self.toasts.update(|t| t.push(Toast { id, text, undo }));
        let toasts = self.toasts;
        leptos::task::spawn_local(async move {
            gloo_timers::future::TimeoutFuture::new(6000).await;
            // A hovered (or focused) toast stays until the reader lets go.
            while HOVERED_TOASTS.with(|h| h.borrow().contains(&id)) {
                gloo_timers::future::TimeoutFuture::new(700).await;
            }
            toasts.update(|t| t.retain(|x| x.id != id));
        });
    }

    pub fn dismiss_toast(&self, id: u64) {
        HOVERED_TOASTS.with(|h| {
            h.borrow_mut().remove(&id);
        });
        self.toasts.update(|t| t.retain(|x| x.id != id));
    }

    pub fn set_toast_hovered(&self, id: u64, hovered: bool) {
        HOVERED_TOASTS.with(|h| {
            if hovered {
                h.borrow_mut().insert(id);
            } else {
                h.borrow_mut().remove(&id);
            }
        });
    }

    pub fn set_banner(&self, kind: BannerKind, text: impl Into<String>) {
        self.banner.set(Some(Banner {
            kind,
            text: text.into(),
            sticky: false,
        }));
    }

    pub fn set_banner_sticky(&self, kind: BannerKind, text: impl Into<String>) {
        self.banner.set(Some(Banner {
            kind,
            text: text.into(),
            sticky: true,
        }));
    }

    /// Clear any non-sticky banner (called when a new update attempt starts).
    pub fn clear_transient_banner(&self) {
        self.banner.update(|b| {
            if b.as_ref().is_some_and(|b| !b.sticky) {
                *b = None;
            }
        });
    }

    pub fn say(&self, text: impl Into<String>) {
        self.announce.set(text.into());
    }

    // -- persistence + URL -------------------------------------------------

    pub fn persist_selection(&self) {
        let _ = storage::save(storage::KEY_SELECTION, &self.selection.get_untracked());
        self.sync_url();
    }

    pub fn persist_overrides(&self) {
        let _ = storage::save(storage::KEY_OVERRIDES, &self.overrides.get_untracked());
    }

    pub fn persist_prefs(&self) {
        let _ = storage::save(storage::KEY_PREFS, &self.prefs.get_untracked());
    }

    /// Keep `?c=` canonical on every selection change (replaceState). Any
    /// `s=` payload is consumed at load time and dropped here.
    pub fn sync_url(&self) {
        let selection = self.selection.get_untracked();
        if selection.is_empty() {
            domx::replace_query("");
        } else {
            domx::replace_query(&format!(
                "?c={}",
                ttcore::share::selection_to_c_param(&selection)
            ));
        }
    }

    // -- undo / redo ---------------------------------------------------------

    fn push_undo(&self, label: &str) {
        let entry = UndoEntry {
            label: label.to_string(),
            selection: self.selection.get_untracked(),
            overrides: self.overrides.get_untracked(),
        };
        self.undo_stack.update(|s| {
            s.undo.push(entry);
            if s.undo.len() > UNDO_MAX {
                s.undo.remove(0);
            }
            s.redo.clear();
        });
    }

    pub fn can_undo(&self) -> bool {
        self.undo_stack.with(|s| !s.undo.is_empty())
    }

    pub fn can_redo(&self) -> bool {
        self.undo_stack.with(|s| !s.redo.is_empty())
    }

    /// Every undoable action funnels through here: one entry on the stack,
    /// mutate, persist, sync URL.
    pub fn act(&self, label: &str, f: impl FnOnce(&mut Vec<String>, &mut OverridesStore)) {
        self.push_undo(label);
        let mut selection = self.selection.get_untracked();
        let mut overrides = self.overrides.get_untracked();
        f(&mut selection, &mut overrides);
        self.selection.set(selection);
        self.overrides.set(overrides);
        self.persist_selection();
        self.persist_overrides();
    }

    pub fn undo(&self) {
        let entry = self.undo_stack.try_update(|s| s.undo.pop()).flatten();
        if let Some(entry) = entry {
            let current = UndoEntry {
                label: entry.label.clone(),
                selection: self.selection.get_untracked(),
                overrides: self.overrides.get_untracked(),
            };
            self.undo_stack.update(|s| s.redo.push(current));
            self.selection.set(entry.selection);
            self.overrides.set(entry.overrides);
            self.persist_selection();
            self.persist_overrides();
            self.toast(format!("Undid: {}", entry.label));
        }
    }

    pub fn redo(&self) {
        let entry = self.undo_stack.try_update(|s| s.redo.pop()).flatten();
        if let Some(entry) = entry {
            let current = UndoEntry {
                label: entry.label.clone(),
                selection: self.selection.get_untracked(),
                overrides: self.overrides.get_untracked(),
            };
            self.undo_stack.update(|s| s.undo.push(current));
            self.selection.set(entry.selection);
            self.overrides.set(entry.overrides);
            self.persist_selection();
            self.persist_overrides();
            self.toast(format!("Redid: {}", entry.label));
        }
    }

    // -- selection -----------------------------------------------------------

    pub fn is_selected(&self, code: &str) -> bool {
        self.selection.with(|s| s.iter().any(|c| c == code))
    }

    pub fn add_course(&self, code: &str) {
        if self.is_selected(code) {
            return;
        }
        let code = code.to_string();
        self.act(&format!("add {code}"), |sel, _| {
            if !sel.contains(&code) {
                sel.push(code.clone());
            }
        });
        // Warn immediately (never block) when the new course clashes.
        let clashing = self.clashing_partners(&code);
        if clashing.is_empty() {
            self.toast_undo(format!("Added {code}"));
        } else {
            self.toast_undo(format!(
                "Added {code} — ⚠ clashes with {}",
                clashing.join(", ")
            ));
        }
    }

    /// Distinct courses this (selected) course clashes with, with day/time.
    pub fn clashing_partners(&self, code: &str) -> Vec<String> {
        let mut out: Vec<String> = Vec::new();
        for c in self.clashes() {
            let other = if c.a == code {
                &c.b
            } else if c.b == code {
                &c.a
            } else {
                continue;
            };
            let entry = format!("{other} ({} {})", c.day.short(), c.a_slot.label());
            if !out.contains(&entry) {
                out.push(entry);
            }
        }
        out
    }

    /// Deselecting keeps the course's custom times: re-adding it (or looking
    /// at it in the master grid) must not silently revert a move. Custom
    /// times are removed explicitly via "My data" or per-meeting resets.
    pub fn remove_course(&self, code: &str) {
        if !self.is_selected(code) {
            return;
        }
        let code = code.to_string();
        self.act(&format!("remove {code}"), |sel, _| {
            sel.retain(|c| c != &code);
        });
        self.removed_upstream.update(|r| r.retain(|c| c != &code));
        self.toast_undo(format!("Removed {code}"));
    }

    pub fn toggle_select(&self, code: &str) {
        if self.is_selected(code) {
            self.remove_course(code);
        } else {
            self.add_course(code);
        }
    }

    // -- overrides -----------------------------------------------------------

    /// Create or update an override. `ov_id` targets an existing override;
    /// otherwise one matching (course, base) is updated in place.
    pub fn apply_override(
        &self,
        course: &str,
        ov_id: Option<u64>,
        base: Option<Meeting>,
        to: Meeting,
        label: &str,
        toast: Option<String>,
    ) {
        let course = course.to_string();
        let now = domx::now_ms();
        self.act(label, |_, ovs| {
            let existing = ovs.items.iter_mut().find(|o| match ov_id {
                Some(id) => o.id == id,
                None => o.course == course && o.base == base,
            });
            match existing {
                Some(o) => o.to = to.clone(),
                None => {
                    ovs.add(&course, base.clone(), to.clone(), now);
                }
            }
        });
        if let Some(text) = toast {
            self.toast_undo(text);
        }
    }

    /// Drag a not-yet-selected course in the master grid: select it *and*
    /// apply the override as one action (one undo step).
    pub fn select_and_override(
        &self,
        course: &str,
        base: Option<Meeting>,
        to: Meeting,
        toast: String,
    ) {
        let course = course.to_string();
        let now = domx::now_ms();
        self.act(&format!("add & move {course}"), |sel, ovs| {
            if !sel.iter().any(|c| c == &course) {
                sel.push(course.clone());
            }
            ovs.add(&course, base.clone(), to.clone(), now);
        });
        self.toast_undo(toast);
    }

    /// Add an extra weekly meeting to a course (base = None ⇒ user-created).
    /// Unlike `apply_override`, this ALWAYS creates a new entry, so a course
    /// can gain any number of additional time slots.
    pub fn add_meeting(&self, course: &str, to: Meeting, toast: String) {
        let course = course.to_string();
        let now = domx::now_ms();
        self.act(&format!("add a meeting to {course}"), |_, ovs| {
            ovs.add(&course, None, to.clone(), now);
        });
        self.toast_undo(toast);
    }

    /// Starting point for newly created meetings: the grid's first day and
    /// slot — derived from the parsed data, never from CMI's current scheme.
    /// (The validation gate guarantees a non-empty slot grid; the fallback
    /// is a generic 09:00–10:00 hour.)
    pub fn default_meeting(&self) -> Meeting {
        let slot = self
            .snapshot
            .with_untracked(|s| s.slot_grid.first().copied())
            .unwrap_or(Slot::new(9 * 60, 10 * 60));
        let day = self.grid_days().first().copied().unwrap_or(Day::Mon);
        Meeting {
            day,
            slot,
            hall: None,
            temp_booking: false,
        }
    }

    pub fn reset_override(&self, id: u64, toast: Option<String>) {
        self.act("reset to CMI's time", |_, ovs| ovs.remove(id));
        if let Some(text) = toast {
            self.toast_undo(text);
        }
    }

    pub fn reset_course_overrides(&self, code: &str) {
        let code = code.to_string();
        self.act(&format!("reset {code} to CMI's times"), |_, ovs| {
            ovs.items.retain(|o| o.course != code);
        });
        self.toast_undo(format!("{code} back on CMI's times"));
    }

    // -- credits -------------------------------------------------------------

    /// Credits used everywhere: your override, else CMI's stated value,
    /// else the campus default of 4.
    pub fn course_credits(&self, course: &Course) -> u8 {
        self.overrides
            .with(|o| o.credits_for(&course.code))
            .unwrap_or_else(|| course.effective_credits())
    }

    /// The user's custom credit value for a course, if any.
    pub fn credits_custom(&self, code: &str) -> Option<u8> {
        self.overrides.with(|o| o.credits_for(code))
    }

    pub fn set_credit_override(&self, code: &str, credits: u8) {
        let code = code.to_string();
        let now = domx::now_ms();
        self.act(&format!("set {code} to {credits} credits"), |_, ovs| {
            ovs.set_credits(&code, credits, now);
        });
        self.toast_undo(format!(
            "{code} now counts as {credits} credit{}",
            if credits == 1 { "" } else { "s" },
        ));
    }

    pub fn remove_credit_override(&self, code: &str) {
        let code = code.to_string();
        self.act(&format!("reset {code} credits"), |_, ovs| {
            ovs.remove_credits(&code);
        });
        self.toast_undo(format!("{code} back on official credits"));
    }

    /// Total number of custom changes (meeting moves + credit overrides).
    pub fn custom_change_count(&self) -> usize {
        self.overrides.with(|o| o.items.len() + o.credits.len())
    }

    /// Resolve all queued conflicts in one undoable step.
    /// `choices[i] = (conflict, keep_mine)`.
    pub fn resolve_conflicts(&self, choices: Vec<(Conflict, bool)>) {
        self.act("resolve timetable conflicts", |_, ovs| {
            for (conflict, keep_mine) in &choices {
                ttcore::merge::resolve_conflict(ovs, conflict, *keep_mine);
            }
        });
        self.conflicts.set(Vec::new());
        self.toast_undo("Conflicts resolved");
    }

    // -- derived data --------------------------------------------------------

    /// Official meetings with the user's overrides layered on top.
    pub fn effective_meetings(&self, course: &Course) -> Vec<EffMeeting> {
        let overrides = self.overrides.get();
        effective_meetings(course, &overrides)
    }

    /// A selected course no longer present upstream ("No longer on CMI's
    /// timetable"). Derived from the snapshot so it survives reloads.
    pub fn is_removed_upstream(&self, code: &str) -> bool {
        self.is_selected(code) && self.snapshot.with(|s| s.course(code).is_none())
    }

    pub fn selected_courses(&self) -> Vec<Course> {
        let snapshot = self.snapshot.get();
        self.selection
            .get()
            .iter()
            .map(|code| {
                snapshot.course(code).cloned().unwrap_or_else(|| {
                    // Removed upstream but still selected: synthesize a stub
                    // so it stays visible with its badge.
                    Course {
                        code: code.clone(),
                        name: code.clone(),
                        instructors: vec![],
                        branches: vec![],
                        credits: None,
                        starts: None,
                        part_of_semester: None,
                        optional_flag: false,
                        status: ScheduleStatus::UnscheduledListed,
                        meetings: vec![],
                    }
                })
            })
            .collect()
    }

    /// Interval-overlap clash detection across all selected meetings, after
    /// overrides. Clashes are warnings, never blockers.
    pub fn clashes(&self) -> Vec<ClashPair> {
        let courses = self.selected_courses();
        let overrides = self.overrides.get();
        let mut all: Vec<(String, Meeting)> = Vec::new();
        for c in &courses {
            for eff in effective_meetings(c, &overrides) {
                all.push((c.code.clone(), eff.meeting));
            }
        }
        let mut out = Vec::new();
        for i in 0..all.len() {
            for j in i + 1..all.len() {
                let (a, ma) = &all[i];
                let (b, mb) = &all[j];
                if a != b && ma.day == mb.day && ma.slot.overlaps(&mb.slot) {
                    out.push(ClashPair {
                        a: a.clone(),
                        b: b.clone(),
                        day: ma.day,
                        a_slot: ma.slot,
                        b_slot: mb.slot,
                    });
                }
            }
        }
        out
    }

    pub fn course_has_clash(&self, code: &str) -> bool {
        self.clashes().iter().any(|c| c.a == code || c.b == code)
    }

    pub fn meeting_has_clash(&self, code: &str, meeting: &Meeting) -> bool {
        self.clashes().iter().any(|c| {
            (c.a == code && c.day == meeting.day && c.a_slot == meeting.slot)
                || (c.b == code && c.day == meeting.day && c.b_slot == meeting.slot)
        })
    }

    /// Would this course fit the current selection without any overlap?
    pub fn fits_schedule(&self, course: &Course) -> bool {
        if self.is_selected(&course.code) {
            return true;
        }
        let overrides = self.overrides.get();
        let mine: Vec<(Day, Slot)> = self
            .selected_courses()
            .iter()
            .flat_map(|c| {
                effective_meetings(c, &overrides)
                    .into_iter()
                    .map(|e| (e.meeting.day, e.meeting.slot))
            })
            .collect();
        effective_meetings(course, &overrides).iter().all(|e| {
            !mine
                .iter()
                .any(|(d, s)| *d == e.meeting.day && s.overlaps(&e.meeting.slot))
        })
    }

    /// The day rows shown in grids: Mon–Fri always, Sat/Sun only when data
    /// mentions them.
    pub fn grid_days(&self) -> Vec<Day> {
        let snapshot = self.snapshot.get();
        let overrides = self.overrides.get();
        let mut days = vec![Day::Mon, Day::Tue, Day::Wed, Day::Thu, Day::Fri];
        for c in &snapshot.courses {
            for e in effective_meetings(c, &overrides) {
                if !days.contains(&e.meeting.day) {
                    days.push(e.meeting.day);
                }
            }
        }
        days.sort_by_key(|d| d.index());
        days
    }

    /// Days for the Halls tab and the free-hall finder: grid days UNION any
    /// day that appears only in hall bookings (e.g. a Saturday seminar) —
    /// parsed hall data must never be silently unviewable.
    pub fn hall_days(&self) -> Vec<Day> {
        let mut days = self.grid_days();
        self.snapshot.with(|s| {
            for booking in &s.hall_bookings {
                if !days.contains(&booking.day) {
                    days.push(booking.day);
                }
            }
        });
        days.sort_by_key(|d| d.index());
        days
    }

    // -- navigation ----------------------------------------------------------

    pub fn set_tab(&self, tab: Tab) {
        self.prefs.update(|p| p.tab = tab);
        self.persist_prefs();
    }

    pub fn goto_developer(&self) {
        domx::set_hash("#/developer");
    }

    pub fn goto_planner(&self) {
        domx::set_hash("#/");
    }

    pub fn update_filters(&self, f: impl FnOnce(&mut Filters)) {
        self.prefs.update(|p| f(&mut p.filters));
        self.persist_prefs();
    }

    pub fn filters(&self) -> Filters {
        self.prefs.with(|p| p.filters.clone())
    }
}

/// Overrides layered onto official meetings (usable outside a reactive
/// context, e.g. in the merge/adopt flow).
pub fn effective_meetings(course: &Course, overrides: &OverridesStore) -> Vec<EffMeeting> {
    let mut out: Vec<EffMeeting> = Vec::new();
    let course_ovs: Vec<&ttcore::model::MeetingOverride> =
        overrides.for_course(&course.code).collect();
    let mut replaced_ids: Vec<u64> = Vec::new();

    for official in &course.meetings {
        match course_ovs.iter().find(|o| {
            o.base.as_ref().is_some_and(|b| b.same_place_time(official))
                && !replaced_ids.contains(&o.id)
        }) {
            Some(o) => {
                replaced_ids.push(o.id);
                out.push(EffMeeting {
                    meeting: o.to.clone(),
                    overridden: true,
                    ov_id: Some(o.id),
                    base: o.base.clone(),
                    user_created: false,
                });
            }
            None => out.push(EffMeeting {
                meeting: official.clone(),
                overridden: false,
                ov_id: None,
                base: Some(official.clone()),
                user_created: false,
            }),
        }
    }

    // User-created meetings (base = None) and stale overrides whose base no
    // longer matches an official meeting still show up as custom meetings.
    for o in course_ovs {
        if replaced_ids.contains(&o.id) {
            continue;
        }
        out.push(EffMeeting {
            meeting: o.to.clone(),
            overridden: true,
            ov_id: Some(o.id),
            base: o.base.clone(),
            user_created: o.base.is_none(),
        });
    }

    out.sort_by_key(|e| (e.meeting.day.index(), e.meeting.slot.start_min));
    out
}

/// Facet matching: OR within a facet, AND across facets.
pub fn course_matches(app: &App, course: &Course, f: &Filters) -> bool {
    if !f.branches.is_empty() && !course.branches.iter().any(|b| f.branches.contains(b)) {
        return false;
    }
    if !f.instructors.is_empty()
        && !course.instructors.iter().any(|i| f.instructors.contains(i))
    {
        return false;
    }
    let overrides = app.overrides.get();
    let eff = effective_meetings(course, &overrides);
    if !f.days.is_empty() && !eff.iter().any(|e| f.days.contains(&e.meeting.day)) {
        return false;
    }
    if !f.slot_starts.is_empty()
        && !eff
            .iter()
            .any(|e| f.slot_starts.contains(&e.meeting.slot.start_min))
    {
        return false;
    }
    if !f.halls.is_empty()
        && !eff
            .iter()
            .any(|e| e.meeting.hall.as_ref().is_some_and(|h| f.halls.contains(h)))
    {
        return false;
    }
    if !f.credits.is_empty() {
        // Facet matches what the user sees — custom credit values included.
        let cr = app.course_credits(course).to_string();
        if !f.credits.contains(&cr) {
            return false;
        }
    }
    if !f.flags.is_empty() {
        let has_custom = !eff.is_empty() && eff.iter().any(|e| e.overridden);
        let matches_flag = f.flags.iter().any(|flag| match flag.as_str() {
            "optional" => course.optional_flag,
            "unscheduled" => course.status == ScheduleStatus::UnscheduledListed,
            "custom" => has_custom,
            _ => false,
        });
        if !matches_flag {
            return false;
        }
    }
    let text = f.text.trim().to_ascii_lowercase();
    if !text.is_empty() {
        let hay = format!(
            "{} {} {}",
            course.code,
            course.name,
            course.instructors.join(" ")
        )
        .to_ascii_lowercase();
        if !hay.contains(&text) {
            return false;
        }
    }
    if f.fits && !app.fits_schedule(course) {
        return false;
    }
    true
}
