[package]
name = "cmi-timetable-sync"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cmi-timetable-sync"
path = "src/main.rs"

[dependencies]
ttcore = { path = "../core", package = "cmi-timetable-core", features = ["html"] }
serde_json.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
